# Generated by Django 2.2.4 on 2019-08-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_viewcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='viewCount',
            new_name='view_cnt',
        ),
    ]
